routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/**
 * Admin routes
 */
Route::namespace('Admin')->group(function () {
	Route::get('admin', 'LoginController@showLoginForm')->name('admin.login');
    Route::get('admin/login', 'LoginController@showLoginForm')->name('admin.login');
    Route::post('admin/login', 'LoginController@login')->name('admin.login');
    Route::get('admin/logout', 'LoginController@logout')->name('admin.logout');
});
Route::group(['prefix' => 'admin', 'middleware' => ['employee'], 'as' => 'admin.' ], function () {
    Route::namespace('Admin')->group(function () {
        Route::group(['middleware' => ['role:admin|superadmin|clerk, guard:employee']], function () {
            Route::get('/dashboard/{reportBase}', 'DashboardController@index')->name('dashboard');
         

			//Appointment
			Route::get('/listingAppointment', 'AdminServiceController@listingAppointment')->name('listingAppointment');
			Route::get('/addAppointment', 'AdminServiceController@addAppointment')->name('addAppointment');
			Route::post('/addNewAppointment', 'AdminServiceController@addNewAppointment');
			Route::get('/editAppointment/{id}', 'AdminServiceController@editAppointment');
			Route::post('/updateAppointment', 'AdminServiceController@updateAppointment');
			Route::post('/deleteAppointment/', 'AdminServiceController@deleteAppointment');

			//Brands
			Route::get('/listingDescription', 'AdminDescriptionController@listingDescription')->name('listingDescription');
			Route::get('/addDescription', 'AdminDescriptionController@addDescription')->name('addDescription');
			Route::post('/addNewDescription', 'AdminDescriptionController@addNewDescription');
			Route::get('/editDescription/{id}', 'AdminDescriptionController@editDescription');
			Route::post('/updateDescription', 'AdminDescriptionController@updateDescription');
			Route::post('/deleteDescription/', 'AdminDescriptionController@deleteDescription');


			Route::get('/listingMedicine', 'AdminMedicineController@listingMedicine')->name('listingMedicine');
			Route::get('/addMedicine', 'AdminMedicineController@addMedicine')->name('addMedicine');
			Route::post('/addNewMedicine', 'AdminMedicineController@addNewMedicine');
			Route::get('/editMedicine/{id}', 'AdminMedicineController@editMedicine');
			Route::post('/updateMedicine', 'AdminMedicineController@updateMedicine');
			Route::post('/deleteMedicine/', 'AdminMedicineController@deleteMedicine');
			
			Route::get('/listingTime', 'AdminTimeController@listingTime')->name('listingTime');
			Route::get('/addTime', 'AdminTimeController@addTime')->name('addTime');
			Route::post('/addNewTime', 'AdminTimeController@addNewTime');
			Route::get('/editTime/{id}', 'AdminTimeController@editTime');
			Route::post('/updateTime', 'AdminTimeController@updateTime');
			Route::post('/deleteTime/', 'AdminTimeController@deleteTime');
			

        });
			Route::group(['middleware' => ['role:admin|superadmin, guard:employee']], function () {
            Route::resource('employees', 'EmployeeController');
            Route::get('employees/{id}/profile', 'EmployeeController@getProfile')->name('employee.profile');
            Route::put('employees/{id}/profile', 'EmployeeController@updateProfile')->name('employee.profile.update');
            Route::resource('roles', 'Roles\RoleController');
            Route::resource('permissions', 'Permissions\PermissionController');
        });
    });
});

/**
 * Frontend routes
 */
Auth::routes();
Route::namespace('Auth')->group(function () {
    Route::get('cart/login', 'CartLoginController@showLoginForm')->name('cart.login');
    Route::post('cart/login', 'CartLoginController@login')->name('cart.login');
    Route::get('logout', 'LoginController@logout');
});

Route::namespace('Front')->group(function () {
    Route::get('/', 'HomeController@index')->name('home');
	Route::get("contact-us", 'ContactusController@index')->name('contactus.index');
	Route::post("contact-us", 'ContactusController@send')->name('contactus.send');
//	Route::get("login", 'HomeController@login')->name('login');
	//Route::post("loginn", 'HomeController@loginn')->name('loginn');
	Route::get("registration", 'HomeController@registration')->name('registration');
	Route::post("register", 'HomeController@register')->name('register');
	Route::get("client", 'HomeController@client')->name('client');
	

});

resources/views/admin/addDescription.blade.php
@extends('layouts.admin.app')
@section('content')
<section class="content">
    <!-- Default box -->
  <div class="box">
    <div class="box-body">
      <h2>Add Description</h2>
         <!-- /.box-header -->
      <div class="box-body">
		    <div class="row">
          <div class="col-md-12">
            <div class="box">
           <!-- /.box-header -->
              <div class="box-body">
                <div class="row">
                  <div class="col-xs-12">
                    <!-- /.box-header -->
                    <!-- form start -->                        
                    <div class="box-body">
                      @if( count($errors) > 0)
                      @foreach($errors->all() as $error)
                      <div class="alert alert-success" role="alert">
                        <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                        <span class="sr-only">Error:</span>
                        {{ $error }}
                      </div>
                      @endforeach
                      @endif
                       {!! Form::open(array('url' =>'admin/addNewDescription', 'method'=>'post', 'class' => 'form-horizontal form-validate', 'enctype'=>'multipart/form-data')) !!}
                      
							        <div class="form-group">
                        <label for="name" class="col-sm-2 col-md-3 control-label">Registration Id</label>
                        <div class="col-sm-10 col-md-4">
							<select class="form-control" name="regid" id="regid">
								<option value="">Select </option>
								  @if($regstn->count() > 0)
								  @foreach($regstn as $row)
								<option value="{{$row->id}}">{{$row->id}}</option>
						          @endforeach	
								  @endif
							</select>
                        </div>
                      </div>

                      <div class="form-group">
                        <label for="name" class="col-sm-2 col-md-3 control-label">{{ trans('labels.Description') }}  </label>
                        <div class="col-sm-10 col-md-8">
                          <textarea id="editor" name="description" class="form-control" rows="10" cols="80"></textarea> <br>
                        </div>
                      </div>

                    
                     <!-- /.box-body -->
        							<div class="box-footer text-center">
        								<button type="submit" class="btn btn-primary">{{ trans('labels.SubmitNews') }}</button>
        								<a href="{{ URL::to('admin/listingDescription')}}" type="button" class="btn btn-default">{{ trans('labels.back') }}</a>
        							</div>
                       <!-- /.box-footer -->
                       {!! Form::close() !!}
                    </div>
                  </div>
                </div>
              </div>
              <!-- /.box-body --> 
            </div>
            <!-- /.box --> 
          </div>
           <!-- /.col --> 
        </div>
        <!-- /.row --> 
      </div>
        <!-- Main row --> 
    </div> 
	</div>
    <!-- /.row --> 
</section>
  <!-- /.content --> 
<script src="{!! asset('resources/views/admin/plugins/jQuery/jQuery-2.2.0.min.js') !!}"></script>
<script type="text/javascript">
		$(function () {
			//bootstrap WYSIHTML5 - text editor
			//
			$("textarea").summernote({height: "400px",});
			//$("textarea").wysihtml5();
			
    });
</script>
@endsection 

resources/views/admin/addMedicine.blade.php
@extends('layouts.admin.app')
@section('content')
<section class="content">
  <div class="box">
    <div class="box-body">
      <h2>Add Review</h2>
      <div class="box-body">
		    <div class="row">
          <div class="col-md-12">
            <div class="box">
              <div class="box-body">
                <div class="row">
                  <div class="col-xs-12">
                    <div class="box-body">
                      @if( count($errors) > 0)
                      @foreach($errors->all() as $error)
                      <div class="alert alert-success" role="alert">
                        <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                        <span class="sr-only">Error:</span>
                        {{ $error }}
                      </div>
                      @endforeach
                      @endif
                       {!! Form::open(array('url' =>'admin/addNewMedicine', 'method'=>'post', 'class' => 'form-horizontal form-validate', 'enctype'=>'multipart/form-data')) !!}
                      
							        <div class="form-group">
                        <label for="name" class="col-sm-2 col-md-3 control-label">Description Id</label>
                        <div class="col-sm-10 col-md-4">
						
							<select class="form-control" name="desid" id="desid">
												<option value="">Select </option>
												@if($dsriptn->count() > 0)
													@foreach($dsriptn as $row)
														<option value="{{$row->id}}">{{$row->id}}</option>
													@endforeach	
												@endif
											
											</select>
						
                         
                        </div>
                      </div>

                      <div class="form-group">
                        <label for="name" class="col-sm-2 col-md-3 control-label">Medicine</label>
                        <div class="col-sm-10 col-md-4">
                         <input type="text" name="medicine" class="form-control field-validate">
                        </div>
                      </div>

                      <div class="form-group">
                        <label for="name" class="col-sm-2 col-md-3 control-label">Medicine Description</label>
                        <div class="col-sm-10 col-md-8">
                          <textarea id="editor" name="medicinedesc" class="form-control" rows="10" cols="80"></textarea> <br>
                        </div>
                      </div>

                      <div class="form-group">
                        <label for="name" class="col-sm-2 col-md-3 control-label">Time</label>
                        <div class="col-sm-10 col-md-4">
                          <tr> 
                            <td><input type="checkbox" name="time[]" class="mode1 mode_checkbox_mode" data-id="" value="Morning"></td>
                            <td>Morning</td>
                          </tr>
                          <tr> 
                            <td><input type="checkbox" name="time[]" class="mode1 mode_checkbox_mode" data-id="" value="Afternoon"></td>
                            <td>Afternoon</td>
                          </tr>
                          <tr> 
                            <td><input type="checkbox" name="time[]" class="mode1 mode_checkbox_mode" data-id="" value="Night"></td>
                            <td>Night</td>
                          </tr>
                        </div>
                      </div>

                    
        							<div class="box-footer text-center">
        								<button type="submit" class="btn btn-primary">{{ trans('labels.SubmitNews') }}</button>
        								<a href="{{ URL::to('admin/listingMedicine')}}" type="button" class="btn btn-default">{{ trans('labels.back') }}</a>
        							</div>
                       {!! Form::close() !!}
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div> 
	</div>
</section>
<script src="{!! asset('resources/views/admin/plugins/jQuery/jQuery-2.2.0.min.js') !!}"></script>
<script type="text/javascript">
		$(function () {
			$("textarea").summernote({height: "400px",});
    });
</script>
@endsection 

resources/views/admin/addPage.blade.php
@extends('layouts.admin.app')
@section('content')
 <section class="content">
   
    <!-- Default box -->
    <div class="box">
        <div class="box-body">
            <h2>Add Page</h2>
          <!-- /.box-header -->
          <div class="box-body">
    <div class="row">
      <div class="col-md-12">
        <div class="box">
         
          <!-- /.box-header -->
          <div class="box-body">
            <div class="row">
              <div class="col-xs-12">
                        <!-- /.box-header -->
                        <!-- form start -->                        
                         <div class="box-body">
                          @if( count($errors) > 0)
                            @foreach($errors->all() as $error)
                                <div class="alert alert-success" role="alert">
                                    <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                                    <span class="sr-only">Error:</span>
                                    {{ $error }}
                                </div>
                             @endforeach
                          @endif
                        
                            {!! Form::open(array('url' =>'admin/addNewPage', 'method'=>'post', 'class' => 'form-horizontal form-validate', 'enctype'=>'multipart/form-data')) !!}
                            
                                 <div class="form-group">
                                  <label for="name" class="col-sm-2 col-md-3 control-label">Template</label>
                                  <div class="col-sm-10 col-md-4">
                                      <select class="form-control" name="type">
                                          <option value="1">Default</option>
                                          <option value="0">Tribute</option>
                                      </select>
                                  </div>
                                </div>

                              <div class="form-group">
                                <label for="name" class="col-sm-2 col-md-3 control-label">{{ trans('labels.PageSlug') }}</label>
                                 <div class="col-sm-10 col-md-4">
                                 {!! Form::text('slug',  '', array('class'=>'form-control field-validate', 'id'=>'slug')) !!}
                                </div>
                              </div>
                              <div class="form-group">
                               <label for="name" class="col-sm-2 col-md-3 control-label">{{ trans('labels.PageName') }}</label>
                                <div class="col-sm-10 col-md-4">
                                 {!! Form::text('name',  '', array('class'=>'form-control field-validate', 'id'=>'name')) !!}
                                </div>
                              </div>
                              <div class="form-group">
                                <label for="name" class="col-sm-2 col-md-3 control-label">{{ trans('labels.Description') }}  </label>
                                <div class="col-sm-10 col-md-8">
                                  <textarea id="editor" name="description" class="form-control" rows="10" cols="80"></textarea> <br>
                                </div>
                              </div>
                               
                                <div class="form-group">
                                  <label for="name" class="col-sm-2 col-md-3 control-label">{{ trans('labels.Status') }}</label>
                                  <div class="col-sm-10 col-md-4">
                                      <select class="form-control" name="status">
                                          <option value="1">{{ trans('labels.Active') }}</option>
                                          <option value="0">{{ trans('labels.InActive') }}</option>
                                      </select>
                                   
                                  </div>
                                </div>
                                
                             
              
                              <!-- /.box-body -->
              <div class="box-footer text-center">
                <button type="submit" class="btn btn-primary">{{ trans('labels.AddPage') }}</button>
                <a href="{{ URL::to('admin/listingCompanies')}}" type="button" class="btn btn-default">{{ trans('labels.back') }}</a>
              </div>
                              <!-- /.box-footer -->
                            {!! Form::close() !!}
                        </div>
              </div>
            </div>
            
          </div>
          <!-- /.box-body --> 
        </div>
        <!-- /.box --> 
      </div>
      <!-- /.col --> 
    </div>
    <!-- /.row --> 
    </div>
    <!-- Main row --> 
    </div> 
  
  </div>
    <!-- /.row --> 
  </section>
  <!-- /.content --> 

<script src="{!! asset('resources/views/admin/plugins/jQuery/jQuery-2.2.0.min.js') !!}"></script>


<script type="text/javascript">
    $(function () {
      
      //bootstrap WYSIHTML5 - text editor
      //
      $("textarea").summernote({height: "400px",});
      //$("textarea").wysihtml5();
      
    });
</script>
@endsection 

resources/views/admin/addTime.blade.php
@extends('layouts.admin.app')
@section('content')
<section class="content">
    <!-- Default box -->
  <div class="box">
    <div class="box-body">
      <h2>Add Time</h2>
         <!-- /.box-header -->
      <div class="box-body">
		    <div class="row">
          <div class="col-md-12">
            <div class="box">
           <!-- /.box-header -->
              <div class="box-body">
                <div class="row">
                  <div class="col-xs-12">
                    <!-- /.box-header -->
                    <!-- form start -->                        
                    <div class="box-body">
                      @if( count($errors) > 0)
                      @foreach($errors->all() as $error)
                      <div class="alert alert-success" role="alert">
                        <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                        <span class="sr-only">Error:</span>
                        {{ $error }}
                      </div>
                      @endforeach
                      @endif
                       {!! Form::open(array('url' =>'admin/addNewTime', 'method'=>'post', 'class' => 'form-horizontal form-validate', 'enctype'=>'multipart/form-data')) !!}
            

                    <div class="form-group">
                        <label for="name" class="col-sm-2 col-md-3 control-label">Time</label>
                        <div class="col-sm-10 col-md-4">
                         <input type="text" name="time" class="form-control field-validate">
                        </div>
                    </div>
					
					
                    <div class="form-group">
                        <label for="name" class="col-sm-2 col-md-3 control-label">Date</label>
                        <div class="col-sm-10 col-md-4">
                            <input readonly class="form-control datepicker field-validate" type="text" name="datee" value="">
                        </div>
                    </div>

                    
                     <!-- /.box-body -->
        							<div class="box-footer text-center">
        								<button type="submit" class="btn btn-primary">{{ trans('labels.SubmitNews') }}</button>
        								<a href="{{ URL::to('admin/listingTime')}}" type="button" class="btn btn-default">{{ trans('labels.back') }}</a>
        							</div>
                       <!-- /.box-footer -->
                       {!! Form::close() !!}
                    </div>
                  </div>
                </div>
              </div>
              <!-- /.box-body --> 
            </div>
            <!-- /.box --> 
          </div>
           <!-- /.col --> 
        </div>
        <!-- /.row --> 
      </div>
        <!-- Main row --> 
    </div> 
	</div>
    <!-- /.row --> 
</section>
  <!-- /.content --> 
<script src="{!! asset('resources/views/admin/plugins/jQuery/jQuery-2.2.0.min.js') !!}"></script>
<script type="text/javascript">
		$(function () {
			//bootstrap WYSIHTML5 - text editor
			//
			$("textarea").summernote({height: "400px",});
			//$("textarea").wysihtml5();
			
    });
</script>
@endsection 

resources/views/admin/dashboard.blade.php
@extends('layouts.admin.app')
<style>
    .chart-pie, .has-fixed-height {
        height: 400px;
    }
</style>
@section('content')
    <section class="content">
        <div class="row">
            <div class="col-md-12">
            </div>
        </div>
       
        <!-- /.row -->
    </section>
    <!-- /.content -->

 
@endsection

resources/views/admin/editDescription.blade.php
@extends('layouts.admin.app')
@section('content')
<section class="content">
    <div class="box">
        <div class="box-body">
            <h2>Edit Details</h2>
           	<div class="box-body">
            <div class="row">
                <div class="col-xs-12">
              		<div class="box box-info">
                       <br>                       
                        @if (count($errors) > 0)
                              @if($errors->any())
                                <div class="alert alert-success alert-dismissible" role="alert">
                                  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                  {{$errors->first()}}
                                </div>
                              @endif
                          @endif
                       
						<div class="panel with-nav-tabs  panel-default">
							
							<div class="panel-body">
								<div class="tab-content">
									<div class="tab-pane fade in active" id="English">
										<div class="box-body">
											{!! Form::open(array('url' =>'admin/updateDescription', 'method'=>'post', 'class' => 'form-horizontal', 'enctype'=>'multipart/form-data')) !!}
											  
						                    {!! Form::hidden('id',  $result['description'][0]->id , array('class'=>'form-control', 'id'=>'id')) !!}

												<div class="form-group">
												  <label for="name" class="col-sm-2 col-md-3 control-label">Register Id</label>
												  <div class="col-sm-10 col-md-4">
													{!! Form::text('regid', $result['description'][0]->regid, array('class'=>'form-control','id'=>'regid','readonly')) !!}
												  </div>
												</div>

												<div class="form-group">
					                                <label for="name" class="col-sm-2 col-md-3 control-label">{{ trans('labels.Description') }}  </label>
					                                <div class="col-sm-10 col-md-8">
					                                  <textarea id="editor" name="description" class="form-control" rows="10" cols="80">{!! $result['description'][0]->description!!}</textarea> <br>
					                                </div>
				                             	</div>

											    <div class="box-footer text-center">
													<button type="submit" class="btn btn-primary">{{ trans('labels.Update') }}</button>
													<a href="{{ URL::to('admin/listingDescription')}}" type="button" class="btn btn-default">{{ trans('labels.back') }}</a>
											    </div>
											{!! Form::close() !!}
										</div>
									</div>
                  				</div>
              				</div>
            			</div>
         			</div>
        		</div>
   			</div>
</section>

<script src="{!! asset('resources/views/admin/plugins/jQuery/jQuery-2.2.0.min.js') !!}"></script>

<script type="text/javascript">
		$(function () {
			
			$("textarea").summernote({height: "400px",});
			
    });
</script>
@endsection 

resources/views/admin/listingAppointment.blade.php
@extends('layouts.admin.app')
@section('content')
<!-- Main content -->
    <section class="content">
    @include('layouts.errors-and-messages')
    <!-- Default box -->
    <div class="box">
        <div class="box-body">
            <h2>Service</h2>
            <div class="row">
              <div class="col-xs-12">
        
                <table class="table table-bordered table-striped">
                  <thead>
                    <tr>
                      <th>ID</th>
                      <th>Register Id</th>
                      <th>date</th>
					  <th>Name</th>
                      <th>Token Number</th>
                      <th>status</th>
                      <th>Action</th>
                    </tr>
                  </thead>
                  <tbody>
                  @if(count($result['appointments'])>0)
                    @foreach ($result['appointments'] as $key=>$appointments)
                        <tr>
                            <td>{{ $appointments->id }}</td>
                            <td>{{ $appointments->regid }}</td>
                            <td>{{ $appointments->datee }}</td>
							<td>{{ $appointments->name }}</td>
                            <td>{{ $appointments->tokenno }}</td>
                            <td>{{ $appointments->status }}</td>
                            <td><a data-toggle="tooltip" data-placement="bottom" title="Edit" href="editAppointment/{{ $appointments->id }}" class="badge bg-light-blue">edit</a> 
                            
                           
                        </tr>
                    @endforeach
                    @else
                       <tr>
                            <td colspan="5">NoRecordFound</td>
                       </tr>
                    @endif
                  </tbody>
                </table>
                <div class="col-xs-12 text-right">
                  {{$result['appointments']->links()}}
                </div>
              </div>
            </div>
          </div>
     </section>  



@endsection

resources/views/admin/listingMedicine.blade.php
@extends('layouts.admin.app')
@section('content')
<!-- Main content -->
    <section class="content">
    @include('layouts.errors-and-messages')
    <!-- Default box -->
    <div class="box">
        <div class="box-body">
            <h2>Descriptions</h2>
            <div class="row">
              <div class="col-xs-12">
                <div class="btn-group pull-right" >
                  <a class="btn btn-sm btn-primary" href="{{ route('admin.addMedicine') }}"><i class="fa fa-plus"></i> Add New</a>
                </div>
                <table class="table table-bordered table-striped">
                  <thead>
                    <tr>
                      <th>ID</th>
                      <th>Description Id</th>
                      <th>Medicines</th>
                      <th>Medicine Description</th>
                      <th>Time</th>
                      <th>Action</th>
                    </tr>
                  </thead>
                  <tbody>
                  @if(count($result['review'])>0)
                    @foreach ($result['review'] as $key=>$review)
                        <tr>
                            <td>{{ $review->id }}</td>
                            <td>{{ $review->desid }}</td>
                            <td>{!! substr($review->medicine,0,200 )!!}</td>
                            <td>{!! substr($review->medicinedesc,0,200 )!!}</td>
                            <td>{{ $review->time }}</td>
                            <td><a data-toggle="tooltip" data-placement="bottom" title="Edit" href="editMedicine/{{ $review->id }}" class="badge bg-light-blue">Edit</a> 
                        </tr>
                    @endforeach
                    @else
                       <tr>
                          <td colspan="5">NoRecordFound</td>
                       </tr>
                    @endif
                  </tbody>
                </table>
                <div class="col-xs-12 text-right">
                  {{$result['review']->links()}}
                </div>
              </div>
            </div>
          </div>
     </section>  



@endsection

resources/views/admin/listingTime.blade.php
@extends('layouts.admin.app')
@section('content')
<!-- Main content -->
    <section class="content">
    @include('layouts.errors-and-messages')
    <!-- Default box -->
    <div class="box">
        <div class="box-body">
            <h2>Time</h2>
            <div class="row">
              <div class="col-xs-12">
                <div class="btn-group pull-right" >
                  <a class="btn btn-sm btn-primary" href="{{ route('admin.addTime') }}"><i class="fa fa-plus"></i> Add New</a>
                </div>
                <table class="table table-bordered table-striped">
                  <thead>
                    <tr>
                      <th>ID</th>
                      <th>Time</th>
                      <th>Date</th>
                      <th>Action</th>
                    </tr>
                  </thead>
                  <tbody>
                  @if(count($result['time'])>0)
                    @foreach ($result['time'] as $key=>$time)
                        <tr>
                            <td>{{ $time->id }}</td>
                            <td>{{ $time->time }}</td>
                            <td>{{ $time->datee }}</td>
                            <td><a data-toggle="tooltip" data-placement="bottom" title="Edit" href="editTime/{{ $time->id }}" class="badge bg-light-blue">Edit</a> 
                        </tr>
                    @endforeach
                    @else
                       <tr>
                          <td colspan="5">NoRecordFound</td>
                       </tr>
                    @endif
                  </tbody>
                </table>
                <div class="col-xs-12 text-right">
                  {{$result['time']->links()}}
                </div>
              </div>
            </div>
          </div>
     </section>  



@endsection