routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/**
 * Admin routes
 */
Route::namespace('Admin')->group(function () {
	Route::get('admin', 'LoginController@showLoginForm')->name('admin.login');
    Route::get('admin/login', 'LoginController@showLoginForm')->name('admin.login');
    Route::post('admin/login', 'LoginController@login')->name('admin.login');
    Route::get('admin/logout', 'LoginController@logout')->name('admin.logout');
});
Route::group(['prefix' => 'admin', 'middleware' => ['employee'], 'as' => 'admin.' ], function () {
    Route::namespace('Admin')->group(function () {
        Route::group(['middleware' => ['role:admin|superadmin|clerk, guard:employee']], function () {
            Route::get('/dashboard/{reportBase}', 'DashboardController@index')->name('dashboard');
         

			//Appointment
			Route::get('/listingAppointment', 'AdminServiceController@listingAppointment')->name('listingAppointment');
			Route::get('/addAppointment', 'AdminServiceController@addAppointment')->name('addAppointment');
			Route::post('/addNewAppointment', 'AdminServiceController@addNewAppointment');
			Route::get('/editAppointment/{id}', 'AdminServiceController@editAppointment');
			Route::post('/updateAppointment', 'AdminServiceController@updateAppointment');
			Route::post('/deleteAppointment/', 'AdminServiceController@deleteAppointment');

			//Brands
			Route::get('/listingDescription', 'AdminDescriptionController@listingDescription')->name('listingDescription');
			Route::get('/addDescription', 'AdminDescriptionController@addDescription')->name('addDescription');
			Route::post('/addNewDescription', 'AdminDescriptionController@addNewDescription');
			Route::get('/editDescription/{id}', 'AdminDescriptionController@editDescription');
			Route::post('/updateDescription', 'AdminDescriptionController@updateDescription');
			Route::post('/deleteDescription/', 'AdminDescriptionController@deleteDescription');


			Route::get('/listingMedicine', 'AdminMedicineController@listingMedicine')->name('listingMedicine');
			Route::get('/addMedicine', 'AdminMedicineController@addMedicine')->name('addMedicine');
			Route::post('/addNewMedicine', 'AdminMedicineController@addNewMedicine');
			Route::get('/editMedicine/{id}', 'AdminMedicineController@editMedicine');
			Route::post('/updateMedicine', 'AdminMedicineController@updateMedicine');
			Route::post('/deleteMedicine/', 'AdminMedicineController@deleteMedicine');
			
			Route::get('/listingTime', 'AdminTimeController@listingTime')->name('listingTime');
			Route::get('/addTime', 'AdminTimeController@addTime')->name('addTime');
			Route::post('/addNewTime', 'AdminTimeController@addNewTime');
			Route::get('/editTime/{id}', 'AdminTimeController@editTime');
			Route::post('/updateTime', 'AdminTimeController@updateTime');
			Route::post('/deleteTime/', 'AdminTimeController@deleteTime');
			

        });
			Route::group(['middleware' => ['role:admin|superadmin, guard:employee']], function () {
            Route::resource('employees', 'EmployeeController');
            Route::get('employees/{id}/profile', 'EmployeeController@getProfile')->name('employee.profile');
            Route::put('employees/{id}/profile', 'EmployeeController@updateProfile')->name('employee.profile.update');
            Route::resource('roles', 'Roles\RoleController');
            Route::resource('permissions', 'Permissions\PermissionController');
        });
    });
});

/**
 * Frontend routes
 */
Auth::routes();
Route::namespace('Auth')->group(function () {
    Route::get('cart/login', 'CartLoginController@showLoginForm')->name('cart.login');
    Route::post('cart/login', 'CartLoginController@login')->name('cart.login');
    Route::get('logout', 'LoginController@logout');
});

Route::namespace('Front')->group(function () {
    Route::get('/', 'HomeController@index')->name('home');
	Route::get("contact-us", 'ContactusController@index')->name('contactus.index');
	Route::post("contact-us", 'ContactusController@send')->name('contactus.send');
//	Route::get("login", 'HomeController@login')->name('login');
	//Route::post("loginn", 'HomeController@loginn')->name('loginn');
	Route::get("registration", 'HomeController@registration')->name('registration');
	Route::post("register", 'HomeController@register')->name('register');
	Route::get("client", 'HomeController@client')->name('client');
	

});

resources/views/layouts/admin/footer.blade.php
<footer class="main-footer">
    <div class="pull-right hidden-xs">
        <b>Version</b> 0.1.0
    </div>
    <strong>Copyright &copy; {{ date('Y') }} - {{ date('Y') + 1 }} <a href="{{config('app.url')}}">{{config('app.name')}}</a>.</strong> All rights
    reserved.
</footer>

resources/views/layouts/admin/header.blade.php
<header class="main-header">
    <a href="{{ route('admin.dashboard', ['reportBase' => 'this_month']) }}" class="logo">
        <span class="logo-mini" style="font-size: 12px;">{{ config('app.name') }}</span>
        <span class="logo-lg">{{ config('app.name') }}</span>
    </a>
    <nav class="navbar navbar-static-top">
        <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </a>
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                <li class="dropdown user user-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <img src="{{ asset('resources/views/admin/images/admin_profile/1499174950.avatar5.png') }}" class="user-image" alt="User Image">
                        <span class="hidden-xs">{{ $user->name }}</span>
                    </a>
                    <ul class="dropdown-menu">
                        <li class="user-header">
                            <img src="{{ asset('resources/views/admin/images/admin_profile/1499174950.avatar5.png') }}" class="img-circle" alt="User Image">
                            <p>
                                {{ $user->name }}
                            </p>
                        </li>
                        <li class="user-footer">
                            <div class="pull-left">
                                <a href="{{ route('admin.employee.profile', $user->id) }}" class="btn btn-default btn-flat">Profile</a>
                            </div>
                            <div class="pull-right">
                                <a href="{{ route('admin.logout') }}" class="btn btn-default btn-flat">Sign out</a>
                            </div>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </nav>
</header>

resources/views/layouts/admin/sidebar.blade.php
<aside class="main-sidebar">
    <section class="sidebar">
        <div class="user-panel">
            <div class="pull-left image">
                <img src="{{ asset('resources/views/admin/images/admin_profile/1499174950.avatar5.png') }}" class="img-circle" alt="User Image">
            </div>
            <div class="pull-left info">
                <p>{{ $user->name }}</p>
                <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
        </div>
        <ul class="sidebar-menu">
			<li class="header">HOME</li>
			<li class="treeview @if(request()->segment(2) == 'listingCoupons' || request()->segment(2) == 'addCoupons'|| request()->segment(2) == 'editCoupons') active @endif">
				<a href="{{ route('admin.dashboard', ['reportBase' => 'this_month']) }}"> <i class="fa fa-home"></i><span> Dashboard</span></a>
			</li>
            <li class=" @if(request()->segment(2) == 'listingAppointment'|| request()->segment(2) == 'editAppointment' || request()->segment(2) == 'addAppointment') active @endif">
                <a href="{{ route('admin.listingAppointment') }}">
                    <i class="fa fa-user"></i> <span>Appointment</span>
                </a>
            </li>
            <li class=" @if(request()->segment(2) == 'listingDescription'|| request()->segment(2) == 'editDescription' || request()->segment(2) == 'addDescription') active @endif">
                <a href="{{ route('admin.listingDescription') }}">
                    <i class="fa fa-sticky-note"></i> <span>Description</span>
                </a>
            </li>
            <li class=" @if(request()->segment(2) == 'listingMedicine'|| request()->segment(2) == 'editMedicine' || request()->segment(2) == 'addMedicine') active @endif">
                <a href="{{ route('admin.listingMedicine') }}">
                    <i class="fa fa-medkit"></i> <span>Medicine</span>
                </a>
            </li>
			<li class=" @if(request()->segment(2) == 'listingTime'|| request()->segment(2) == 'editTime' || request()->segment(2) == 'addTime') active @endif">
                <a href="{{ route('admin.listingTime') }}">
                    <i class="fa fa-medkit"></i> <span>Time</span>
                </a>
            </li>
        </ul>

    </section>
</aside>